class Config():
    MEMORY_MSG_BUFFER = 2
    N_VARIANTS_OF_MULTI_QUERY = 1
    MAX_TRIES_TO_CORRECT_JSON_STRING = 3
    MINIMUM_CUTOFF_THRESHOLD_FOR_SIMILARITY_SEARCH  :float = 0.0

    #EMBEDDER
    USE_OPEN_AI_EMBEDDER = True
    #CHAT_MODEL
    USE_OPEN_AI_CHAT_MODEL = True

    #VIDEO PROCESSING
    VIDEO_CAPTURE_FRAME_RATE = 1000
    FIND_K_RELEVANT_FRAMES_IN_VIDEO = 1
    SAVE_VIDEO_WITH_NAME = "abc.mp4"
    SAVE_VIDEO_FILE_IN_FOLDER_NAME = "data"
    SAVE_VIDEO_FILE_ON_ROOT_PATH = "./"+SAVE_VIDEO_FILE_IN_FOLDER_NAME+"/"
    SAVE_FILE_NAME_WITH_HEAD = "frame"
    ST_CLIP_MODEL_PATH = './models/ST-clip'

    #Unused
    FETCH_K_DOCUMENTS_FOR_EACH_QUERY = 3